# Generated by Django 5.2.16 on 2026-07-17 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя пользователя, отправившего сообщение', max_length=100, verbose_name='Имя отправителя')),
                ('email', models.EmailField(help_text='Email отправителя для обратной связи', max_length=254, verbose_name='Email')),
                ('text', models.TextField(help_text='Содержание сообщения', verbose_name='Текст сообщения')),
                ('is_read', models.BooleanField(default=False, help_text='Флаг прочтения сообщения администратором', verbose_name='Прочитано')),
                ('response_deadline', models.DateTimeField(blank=True, help_text='Срок, до которого необходимо ответить на сообщение', null=True, verbose_name='Дедлайн ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при изменении', verbose_name='Дата обновления')),
                ('parent_message', models.ForeignKey(blank=True, help_text='Сообщение, на которое дан ответ (None для корневых)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedback.message', verbose_name='Родительское сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent_message'], name='feedback_me_parent__5f1fba_idx'), models.Index(fields=['is_read'], name='feedback_me_is_read_ad25e3_idx'), models.Index(fields=['response_deadline'], name='feedback_me_respons_355a66_idx'), models.Index(fields=['-created_at'], name='feedback_me_created_a84627_idx')],
            },
        ),
    ]
